# 체크 예외 기본 이해

- ``Exception``과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다. 단 ``RuntimeException``은 예외로 한다.
- 체크 예외는 잡아서 처리하거나, 또는 밖으로 던지도록 선언해야한다. 그렇지 않으면 컴파일 오류가 발생한다

### CheckedTest

```java
@Slf4j
class CheckedTest {

    @Test
    void checked_catch(){
        Service service = new Service();
        service.callCatch();
    }
    @Test
    void checked_throw(){
        Service service = new Service();
        assertThatThrownBy(() -> service.callThrow())
                .isInstanceOf(MyCheckedException.class);
    }

    /**
     * Exception을 상속받은 예외는 체크 예외가 된다.
     * MyCheckedException super(message) ->  Exception super(message) -> Throwable detailMessage 저장
     * getMessage() -> return detailMessage
     */
    static class MyCheckedException extends Exception{
        public MyCheckedException(String message) {
            super(message);
        }
    }
    static class MyCheckedException2 extends MyCheckedException{
        public MyCheckedException2(String message) {
            super(message);
        }
    }

    /**
     * checked 예외는 예외를 잡아서 처리하거나, 던지거나 둘중 하나를 필수로 선택해야 한다.
     */
    static class Service{
        Repository repository = new Repository();

        /**
         * 예외를 잡아서 처리하는 코드
         */
        public void callCatch(){
           try {
               repository.call();
           }
           catch (MyCheckedException e){
               // 예외 처리 로직
               // e.getMessage() return detailMessage
               log.info("예외처리, message={}", e.getMessage(), e);
           }
        }

        /**
         * 체크 예외를 밖으로 던지는 코드
         * 체크 예외는 예외를 잡지 않고 밖으로 던질려면 throws
         * @throws MyCheckedException
         */
        public void callThrow() throws MyCheckedException{
            repository.call();
        }
    }

    /**
     * 체크 예외는 잡거나 던지거나 둘중 하나이다.
     * throw : 실질적으로 예외를 던진다.
     * throws : 메서드 시그니처에 컴파일러가 해당 예외를 인지하도록 명시한다. (하위 예외 포함)
     */
    static class Repository {
        public void call() throws MyCheckedException{
            throw new MyCheckedException("ex");
        }
        public void call2() throws MyCheckedException{
            throw new MyCheckedException2("ex2");
        }
    }
}
```

Exception을 상속받은 예외는 체크 예외가 된다.
```java
static class MyCheckedException extends Exception {
    public MyCheckedException(String message) {
        super(message);
    }
}
```
- ``MyCheckedException``는 ``Exception``을 상속받았다. ``Exception``을 상속받으면 체크 예외가 된다.
- ``RuntimeException``을 상속받으면 언체크 예외가 된다. 
- 예외가 제공하는 여러가지 기본 기능이 있는데, 그 중에 오류 메시지를 보관하는 기능도 있다.
- 예제에서 보는 것 처럼 생성자를 통해서 해당 기능을 그대로 사용하면 편리하다.
- super -> Exception(String message) super -> Throwable(String message) detailMessage = message
- getMessage() -> return detailMessage(Throwable 멤버 변수)

예외를 잡아서 처리하는 코드를 실행해보자.
```java
@Test
void checked_catch() {
     Service service = new Service();
     service.callCatch();
}
```
- ``service.callCatch()``에서 예외를 처리했기 때문에 테스트 메서드까지 예외가 올라오지 않는다.

실행 분석 
```text

test ➡️ service.callCatch() ➡️ repository.call() [예외 발생, 던짐]
test ⬅️ service.callCatch() [예외 처리] ⬅️ repository.call()
test [정상 흐름] ⬅️ service.callCatch() ⬅️ repository.call()

Repository.call() 에서 MyUncheckedException 예외가 발생하고, 그 예외를 Service.callCatch()
에서 잡는 것을 확인할 수 있다

log.info("예외 처리, message={}", e.getMessage(), e);

실행 결과 
[Test worker] INFO hello.jdbc.exception.basic.CheckedTest - 예외 처리, message=ex
hello.jdbc.exception.basic.CheckedTest$MyCheckedException: ex
hello.jdbc.exception.basic.CheckedTest$MyCheckedException: ex
at 
hello.jdbc.exception.basic.CheckedTest$Repository.call(CheckedTest.java:64)
at 
hello.jdbc.exception.basic.CheckedTest$Service.callCatch(CheckedTest.java:45)
at hello.jdbc.exception.basic.CheckedTest.checked_catch(CheckedTest.java:14)

실행 결과 로그를 보면 첫줄은 우리가 남긴 로그가 그대로 남는 것을 확인할 수 있다
그런데 두 번째 줄 부터 예외에 대한 스택 트레이스가 추가로 출력된다.

log.info("예외 처리, message={}", e.getMessage(), e); ⬅️ 여기서 마지막에 있는 e 부분이다.
```

체크 예외를 잡아서 처리하는 코드
```java
try {
    repository.call();
} 
catch (MyCheckedException e) {
    //예외 처리 로직
}
```
- 체크 예외를 잡아서 처리하려면 ``catch(..)``를 사용해서 예외를 잡으면 된다
- 여기서는 ``MyCheckedException``예외를 잡아서 처리한다.

catch는 해당 타입과 그 하위 타입을 모두 잡을 수 있다
```java
try {
    repository.call();
} 
catch (Exception e) {
    //예외 처리 로직
}
```
- ``catch``에 ``MyCheckedException``의 상위 타입인 ``Exception``을 적어주어도 ``MyCheckedException``을 잡을 수 있다.
- ``catch``에 예외를 지정하면 해당 예외와 그 하위 타입 예외를 모두 잡아준다.

예외를 처리하지 않고, 밖으로 던지는 코드를 살펴보자.
```java
@Test
void checked_throw() {
     Service service = new Service();
     assertThatThrownBy(() -> service.callThrow())
     .isInstanceOf(MyCheckedException.class);
}
```
- ``service.callThrow()``에서 예외를 처리하지 않고, 밖으로 던졌기 때문에 예외가 테스트 메서드까지 올라온다.
- 테스트에서는 기대한 것 처럼 ``MyCheckedException``예외가 던져지면 성공으로 처리한다.

실행 분석 
```text
test ➡️ service.callThrow() ➡️ repository.call() [예외 발생, 던짐]
test ⬅️ service.callThrow() [예외 던짐] ⬅️ repository.call()
3test [예외 도착] ⬅️ service.callThrow() ⬅️ repository.call()
```

체크 예외를 밖으로 던지는 코드
```java
public void callThrow() throws MyCheckedException {
    repository.call();
}
```
- 체크 예외를 처리할 수 없을 때는 ``method() throws 예외``을 사용해서 밖으로 던질 예외를 필수로 지정해주어야 한다.

체크 예외를 밖으로 던지지 않으면 컴파일 오류 발생
```java
public void callThrow() {
    repository.call();
}
```
- ``throws``를 지정하지 않으면 컴파일 오류가 발생한다.
- 체크 예외의 경우 예외를 잡아서 처리하거나 또는 t``throws``를 지정해서 예외를 밖으로 던진다는 선언을 필수로
  해주어야 한다.

참고로 체크 예외를 밖으로 던지는 경우에도 해당 타입과 그 하위 타입을 모두 던질 수 있다
```java
public void callThrow() throws Exception {
    repository.call();
}
```

체크 예외의 장단점
```text
체크 예외는 예외를 잡아서 처리할 수 없을 때, 예외를 밖으로 던지는 throws 예외 를 필수로 선언해야 한다. 그렇지
않으면 컴파일 오류가 발생한다. 이것 때문에 장점과 단점이 동시에 존재한다.

장점: 개발자가 실수로 예외를 누락하지 않도록 컴파일러를 통해 문제를 잡아주는 훌륭한 안전 장치이다.
단점: 하지만 실제로는 개발자가 모든 체크 예외를 반드시 잡거나 던지도록 처리해야 하기 때문에, 너무 번거로운
일이 된다. 크게 신경쓰고 싶지 않은 예외까지 모두 챙겨야 한다.
```